/**
 * Prompt templates for AI-powered TTP extraction and ATT&CK mapping.
 */

export interface CandidateTTP {
  description: string;
  tools: string[];
  artifacts: string[];
}

/**
 * Build a prompt for extracting Tactics, Techniques, and Procedures (TTPs) from a threat report.
 */
export function buildTtpExtractionPrompt(reportText: string): { system: string; user: string } {
  const system = `You are a MITRE ATT&CK specialist and detection engineer analyzing threat intelligence reports to extract behavioral patterns.

Your task is to identify all Tactics, Techniques, and Procedures (TTPs) described in the report. Focus on:
- What actions the attacker took (not just IOCs)
- How they accomplished their objectives
- What artifacts they left behind
- Where detection opportunities exist

For each TTP, provide:
1. description: Clear summary of the behavior (30-80 words)
2. tools: Array of tools/malware used (e.g., ["Mimikatz", "PsExec", "Cobalt Strike"])
3. targetPlatforms: Array of affected platforms (e.g., ["Windows", "Linux", "macOS", "Network"])
4. artifacts: Array of artifacts generated by this TTP
   - type: file, registry, event_log, network, process, other
   - description: What artifact is created/modified
   - value: Specific value if known (e.g., "HKLM\\Software\\Microsoft\\...")
5. detectionOpportunities: Array of detection strategies (3-5 ideas)
6. confidence: high (explicitly described), medium (implied), low (inferred/possible)

EXAMPLES OF GOOD TTPs:
- "Attacker used PowerShell to download a second-stage payload from a remote server, executing it in memory to avoid disk-based detection."
- "Credential dumping was performed using Mimikatz, targeting LSASS memory to extract plaintext passwords and NTLM hashes."
- "Lateral movement via PsExec, creating a service on remote hosts to execute malicious payloads with SYSTEM privileges."

ARTIFACTS EXAMPLES:
- File: Dropper executable written to %TEMP%, named "update.exe"
- Registry: Persistence key created at HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run
- Event Log: Windows Event ID 4688 (process creation) for suspicious command line
- Network: HTTP POST to C2 server every 60 seconds with base64-encoded data
- Process: powershell.exe with encoded command parameter

DETECTION OPPORTUNITIES EXAMPLES:
- Monitor for PowerShell with network connections and encoded commands
- Alert on LSASS memory access by non-system processes
- Detect PsExec service creation on multiple hosts in short time window
- Watch for new services with suspicious paths or names
- Track base64-encoded command-line arguments

OUTPUT FORMAT (strict JSON):
{
  "ttps": [
    {
      "description": "The attacker established persistence by creating a Registry Run key pointing to a malicious executable in the user's Temp directory. This ensures the payload is executed on every user login.",
      "tools": ["Custom Dropper"],
      "targetPlatforms": ["Windows"],
      "artifacts": [
        {
          "type": "registry",
          "description": "Persistence key created in HKCU Run",
          "value": "HKCU\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run\\\\WindowsUpdate"
        },
        {
          "type": "file",
          "description": "Malicious executable dropped in Temp directory",
          "value": "%TEMP%\\\\wupdater.exe"
        },
        {
          "type": "event_log",
          "description": "Windows Event ID 4657 (registry value modification)"
        }
      ],
      "detectionOpportunities": [
        "Monitor Registry Run keys for new entries with unusual paths",
        "Alert on executables written to Temp with network activity",
        "Track Event ID 4657 for suspicious registry modifications",
        "Baseline normal Run key entries and alert on deviations",
        "Correlate new Run key with unsigned or low-reputation executable"
      ],
      "confidence": "high"
    }
  ]
}

IMPORTANT:
- Focus on behaviors, not just IOCs (IOCs are extracted separately)
- Each TTP should be actionable for detection engineering
- Provide specific detection opportunities that can be implemented in SIEM/EDR
- If multiple stages exist (initial access, persistence, lateral movement), create separate TTP entries
- Confidence "high" requires explicit description in report, not inference`;

  const user = `Extract all Tactics, Techniques, and Procedures (TTPs) from the following threat intelligence report. Focus on attacker behaviors and detection opportunities.

REPORT:
${reportText}

Provide the TTP extraction results in strict JSON format as specified.`;

  return { system, user };
}

/**
 * Build a prompt for mapping TTPs to MITRE ATT&CK techniques.
 */
export function buildAttackMappingPrompt(ttps: CandidateTTP[]): { system: string; user: string } {
  const system = `You are a MITRE ATT&CK expert. Your task is to map behavioral patterns (TTPs) to the most specific and accurate MITRE ATT&CK technique IDs.

MAPPING RULES:
1. Prefer subtechniques over parent techniques
   - GOOD: T1059.001 (PowerShell)
   - AVOID: T1059 (Command and Scripting Interpreter) when subtechnique exists
2. Use the most specific technique that matches the behavior
3. Include the tactic (Initial Access, Persistence, Defense Evasion, etc.)
4. Provide clear reasoning for the mapping
5. Suggest appropriate detection rule formats:
   - sigma: For host-based detection (process, registry, file events)
   - yara: For file/memory-based malware detection
   - suricata: For network-based detection

For each TTP, provide:
1. techniqueId: MITRE ATT&CK ID (format: T1234 or T1234.001)
2. techniqueName: Full technique name (e.g., "PowerShell - T1059.001")
3. tactic: Primary tactic (e.g., "Execution", "Persistence")
4. confidence: high (exact match), medium (close match), low (best guess)
5. reasoning: Why this mapping is appropriate (20-40 words)
6. suggestedRuleFormats: Array of suitable detection formats

OUTPUT FORMAT (strict JSON):
{
  "mappings": [
    {
      "techniqueId": "T1059.001",
      "techniqueName": "PowerShell",
      "tactic": "Execution",
      "confidence": "high",
      "reasoning": "TTP explicitly describes PowerShell used to download and execute payload in memory, matching T1059.001 definition precisely.",
      "suggestedRuleFormats": ["sigma"]
    },
    {
      "techniqueId": "T1547.001",
      "techniqueName": "Registry Run Keys / Startup Folder",
      "tactic": "Persistence",
      "confidence": "high",
      "reasoning": "TTP describes creation of HKCU Run registry key for persistence, which is the canonical example of T1547.001.",
      "suggestedRuleFormats": ["sigma"]
    },
    {
      "techniqueId": "T1003.001",
      "techniqueName": "LSASS Memory",
      "tactic": "Credential Access",
      "confidence": "high",
      "reasoning": "TTP describes credential dumping via LSASS memory access, which directly matches T1003.001 (OS Credential Dumping: LSASS Memory).",
      "suggestedRuleFormats": ["sigma", "yara"]
    }
  ]
}

DETECTION FORMAT GUIDANCE:
- sigma: Process creation, registry modifications, file events, authentication logs
- yara: Malware file signatures, memory patterns, PE characteristics
- suricata: Network traffic patterns, C2 communication, HTTP/TLS behavior

IMPORTANT:
- Always check if a subtechnique exists before using parent technique
- Each mapping should enable detection engineering
- If behavior matches multiple techniques, choose the most specific
- Confidence "high" requires strong alignment with ATT&CK definition`;

  const ttpList = ttps.map((ttp, idx) => {
    const tools = ttp.tools.length > 0 ? `\n   Tools: ${ttp.tools.join(', ')}` : '';
    const artifacts = ttp.artifacts.length > 0 ? `\n   Artifacts: ${ttp.artifacts.join(', ')}` : '';
    return `${idx + 1}. ${ttp.description}${tools}${artifacts}`;
  }).join('\n\n');

  const user = `Map the following TTPs to MITRE ATT&CK techniques. Choose the most specific technique ID available.

TTPS TO MAP:
${ttpList}

Provide the ATT&CK mapping results in strict JSON format as specified.`;

  return { system, user };
}
