/**
 * ATT&CK Navigator layer export.
 *
 * Wraps the existing coverage metrics infrastructure from
 * `@/testing/coverage-metrics.js` with file I/O capabilities and
 * customizable layer options. Produces Navigator JSON layers suitable
 * for import into the MITRE ATT&CK Navigator.
 */

import { writeFileSync, mkdirSync } from 'fs';
import { dirname } from 'path';

import type { GeneratedRule } from '@/types/detection-rule.js';
import type { AttackMappingResult } from '@/types/extraction.js';
import {
  calculateCoverageMetrics,
} from '@/testing/coverage-metrics.js';
import type { AttackNavigatorLayer } from '@/testing/coverage-metrics.js';

// ---------------------------------------------------------------------------
// Public Types
// ---------------------------------------------------------------------------

export interface NavigatorExportOptions {
  /** Name for the Navigator layer. Default: "DetectForge Coverage" */
  layerName?: string;
  /** Description for the Navigator layer. */
  description?: string;
  /** Whether to show sub-techniques in the layer. Default: true */
  showSubtechniques?: boolean;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate an ATT&CK Navigator layer object from generated rules and
 * ATT&CK mapping results.
 *
 * Uses `calculateCoverageMetrics` internally to determine technique
 * coverage, then applies any custom options (layer name, description)
 * on top of the base layer.
 *
 * @param rules    - Generated detection rules.
 * @param mappings - ATT&CK mapping results from extraction.
 * @param options  - Optional layer customization.
 * @returns An ATT&CK Navigator layer object.
 */
export function generateNavigatorLayer(
  rules: GeneratedRule[],
  mappings: AttackMappingResult[],
  options?: NavigatorExportOptions,
): AttackNavigatorLayer {
  const metrics = calculateCoverageMetrics(rules, mappings);
  const layer = { ...metrics.navigatorLayer };

  const opts: Required<NavigatorExportOptions> = {
    layerName: options?.layerName ?? 'DetectForge Coverage',
    description:
      options?.description ??
      `Detection coverage: ${metrics.coveragePercentage}% of identified techniques. Generated by DetectForge.`,
    showSubtechniques: options?.showSubtechniques ?? true,
  };

  // Apply custom options
  layer.name = opts.layerName;
  layer.description = opts.description;

  // Filter out sub-techniques if showSubtechniques is disabled
  if (!opts.showSubtechniques) {
    layer.techniques = layer.techniques.filter(
      t => !t.techniqueID.includes('.'),
    );
  }

  return layer;
}

/**
 * Write an ATT&CK Navigator layer to a JSON file on disk.
 *
 * Creates parent directories if they do not already exist.
 *
 * @param rules      - Generated detection rules.
 * @param mappings   - ATT&CK mapping results from extraction.
 * @param outputPath - Absolute or relative path for the output file.
 * @param options    - Optional layer customization.
 */
export function writeNavigatorLayer(
  rules: GeneratedRule[],
  mappings: AttackMappingResult[],
  outputPath: string,
  options?: NavigatorExportOptions,
): void {
  const layer = generateNavigatorLayer(rules, mappings, options);
  const json = JSON.stringify(layer, null, 2);
  const dir = dirname(outputPath);
  mkdirSync(dir, { recursive: true });
  writeFileSync(outputPath, json, 'utf-8');
}
